### ISSUE TITLE
FileNotFoundError: [WinError 3]

### ISSUE THREAD

**Issue by M0dred** [fgeek/pyfiscan#100]
$ python3 -V
Python 3.7.4

OS: Win10

$ python3 pyfiscan.py
[INFO/SpawnPoolWorker-1] child process calling self.run()
[INFO/SpawnPoolWorker-2] child process calling self.run()
[INFO/SpawnPoolWorker-3] child process calling self.run()
[INFO/SpawnPoolWorker-4] child process calling self.run()
[INFO/Process-5] child process calling self.run()
ERROR:root:Traceback (most recent call last):
  File "E:\Git\opt\pyfiscan\pyfiscan.py", line 172, in populate_predefined
    dirs = (startdir + '/' + d.name for d in os.scandir(startdir))
FileNotFoundError: [WinError 3] ϵͳ▒Ҳ▒▒▒ָ▒▒▒▒·▒▒▒▒: '/home'

[INFO/Process-5] process shutting down
[INFO/SpawnPoolWorker-5:1] child process calling self.run()
[INFO/Process-5] process exiting with exitcode 0

**Comment by fgeek** [comment]
This program is for Linux only. Might work in some BSD-systems, but haven't tested.
