### ISSUE TITLE
Add support for OpenCart

### ISSUE THREAD

**Issue by Fogelholk** [fgeek/pyfiscan#65]
index.php and admin/index.php:
Currently latest 2.0-branch version (currently updated):
> define('VERSION', '2.0.1.1');

Latest 1.5-branch version (no longer updated):
> define('VERSION', '1.5.6.4');

Latest 1.4-branch version (no longer updated):
> define('VERSION', '1.4.9.5');

**Comment by fgeek** [comment]
@Fogelholk Can you retest with following, thanks?
```
regexp: ["define\\('VERSION',[ \t]'(?P<version>[0-9.]+)"]
```

**Comment by Fogelholk** [comment]
Seems to be working perfectly! Thanks!
