### ISSUE TITLE
Breaking WPScan License Agreement

### ISSUE THREAD

**Issue by ethicalhack3r** [fgeek/pyfiscan#66]
You are breaking the WPScan license with these commits:

https://github.com/fgeek/pyfiscan/commit/59b5a8c622c4c9052cca5b461793e2931be4766e

and

https://github.com/fgeek/pyfiscan/blob/master/yamls/wordpress-plugins.yml

**Comment by fgeek** [comment]
Both removed as GPL and BSD can't be used in this way. As discussed in IRC I will add detection (in this case fingerprints) from my own research and sadly this work is overlapping with wpvulndb and I don't want to use my time to contribute this research/information back after the communication we had before. I still do consider my work important to WPScan and I am (in some level) sad that you felt it as "nothing". I am also going to use these fingerprints and information I have gathered from various sources (e.g. mailing lists) as a input to other projects I am working on as well so I really can't depend on vulnerability database, which might not be public and/or free tomorrow.

I still constantly see missing issues and errorious data in WPScan database, which is of course normal in this kind of work/research but you should really appreciate contributations from others.

https://github.com/fgeek/pyfiscan/commit/80a36a81c1150134e1b9d9cb2d7c97d5ec4f1763
https://github.com/fgeek/pyfiscan/commit/6b3057d6ad055655888bd80485cac41e144f3bd3
https://github.com/fgeek/pyfiscan/commit/054a9c26fb0b17140622f2eb3fb9b2588c5bcbb1

I am anyways adding CVEs to Debian security tracker and tools like pyfiscan so this is really not a problem for me (have been doing it for over 5 years or so). This only changes the dependencies and co-operation between two open source software projects.
