### ISSUE TITLE
update installation instructions

### ISSUE THREAD

**Issue by zxyz** [fgeek/pyfiscan#90]
with debian stretch the installation is much simpler and no pip and dev packages are needed.

enable backports (for the scandir package) with e. g. adding the following line to /etc/apt/sources.list:
`deb http://deb.debian.org/debian stretch-backports main contrib non-free`

then:

`sudo apt install --no-install-recommends git python-scandir python-jinja2 python-pretty-yaml python-docopt`

`git clone https://github.com/fgeek/pyfiscan.git && cd pyfiscan`

`./pyfiscan.py -r /var/www`

voila :)

btw: tnx for pyfiscan!

**Comment by fgeek** [comment]
Thank you for your feedback and sorry for late response. I'll update instructions in near future.
