### ISSUE TITLE
Import error: No module named 'docopt'

### ISSUE THREAD

**Issue by alvahdati** [fgeek/pyfiscan#96]
hi. i am new to this script. i installed the way you said, but as i run the script on the host i get the following error: Import error: No module named 'docopt'
as i run the:
pip2 install -r requirements.lst
line i receive: dcopt already installed.
any suggestions?

**Comment by alvahdati** [comment]
i have the same issue even with the instructions given here:
https://github.com/fgeek/pyfiscan/issues/90#issue-288117617
i'm on kali linux.

**Comment by fgeek** [comment]
Thanks for the issue report. Instructions updated. Please retest.
